language: shell

os:
  - linux

env:
  - PYTHON_VERSION=3.7

install:
  - source script/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - pip install numpy
  - pip install coverage
  - pip install flake8 codecov
  - pip install sphinx sphinx_rtd_theme
script:
  - flake8 .
  - python -m unittest discover
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
