language: python

os:
  - linux

env:
  - PYTHON_VERSION=3.7
  
python:  
  - 3.7

install:
  - source script/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - pip install numpy
  - pip install coverage
  - pip install flake8 codecov
  - pip install sphinx sphinx_rtd_theme
  - pip install -U tox-travis

script:
  - flake8 .
  - tox
    #- python -m unittest discover
    #- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
