language: python

os:
  - linux

env:
  - PYTHON_VERSION=3.7
  
python:  
  - 3.7

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

  
install:
  - source script/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - pip install numpy
  - pip install coverage
  - pip install codacy-coverage
  - pip install flake8 codecov
  - pip install sphinx sphinx_rtd_theme
  - pip install -U tox-travis

script:
  - flake8 .
  - tox
    #- python -m unittest discover
    #- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - bash <(curl -s https://codecov.io/bash) 
  - coverage xml
  - python-codacy-coverage -r coverage.xml
