language: shell

os:
  - linux
  - windows

env:


install:
  - pip install coverage
  - pip install flake8 codecov
  - pip install sphinx sphinx_rtd_theme
script:
  - flake8 .
  - python setup.py test
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - codecov
